### PR TITLE
Plantinfo

### PR DESCRIPTION
**Pull request by h4rsham**
Created plantinfo page, still need to connect it to backend so that the relevant information is pulled and displayed from our database

### CODE REVIEW

**Review by DeeqaJamalini — DISMISSED** [review]
harsham copied me ughhh

**Review by MateenSQ — DISMISSED** [review]
SBTM

**Review by MateenSQ — APPROVED** [review]
S'alright

**Review by DeeqaJamalini — APPROVED** [review]
help

**Review by spiralnebulam31 — APPROVED** [review]
Everything looks great

**Pull request merged**
